### PR TITLE
update to the latest code, ensure travis job passes

### PR DESCRIPTION
**Pull request by seth-priya**
This changes only pulls in the latest changes from upstream.

I have confirmed that the Travis job passes on Intel now (one on the original PR shows a failure)
https://travis-ci.org/seth-priya/luajit2/jobs/660927250

The latest code builds successfully on ppc64le and all tests from the luajit2-test-suite pass as well!

### CODE REVIEW

**Comment by edmondsw** [comment]
@siddhesh thanks for your help here. The point is to bump https://github.com/openresty/luajit2/pull/77 to clear the Travis failure that is currently showing there. Maybe that will help get that PR some more attention. If there's anything else you can do to help get that openresty/luajit2 PR reviewed and merged, thanks in advance!

**Comment by siddhesh** [comment]
Done!

**Comment by seth-priya** [comment]
thanks @siddhesh !

**Comment by siddhesh** [comment]
@seth-priya I've invited you to collaborate on this repo.  That way you'll be able to push changes to this branch on your own without having to wait for me unnecessarily to gate them.

**Comment by seth-priya** [comment]
thanks @siddhesh , appreciate that!

**Pull request merged**
